import { lightingRigSchema } from './model.js';

const primaryFireSignal = {
  kind: 'seeded-flicker' as const,
  seed: 8117,
  frequencyHz: 5.2,
  intensityMinimumMultiplier: 0.82,
  intensityMaximumMultiplier: 1.12,
  colorTemperatureMinimumKelvin: 1300,
  colorTemperatureMaximumKelvin: 1850,
  interpolation: 'smooth' as const,
};

export function createFirelitInteriorLightingRig() {
  return lightingRigSchema.parse({
    schemaVersion: 1,
    id: 'lighting.firelit-interior',
    exposure: { look: 'AgX - Medium High Contrast', coherentAcrossShots: true },
    worldColor: [0.004, 0.002, 0.001],
    lights: [
      {
        id: 'hearth-source-practical',
        type: 'point',
        position: [-1.8, 0.72, 3.18],
        color: [1, 0.16, 0.025],
        energy: 190,
        sizeMeters: 0.22,
        purpose: 'practical',
        temporalSignalId: 'primary-fire',
        visibleSourceRole: 'primary-fire',
        temporalModulation: primaryFireSignal,
      },
      {
        id: 'fire-shaped-key',
        type: 'area',
        position: [-1.05, 1.2, 2.7],
        target: [1.75, 1.35, 2.02],
        color: [1, 0.2, 0.04],
        energy: 125,
        sizeMeters: 1.15,
        purpose: 'key',
        temporalSignalId: 'primary-fire',
        temporalModulation: primaryFireSignal,
      },
      {
        id: 'fire-ground-bounce',
        type: 'area',
        position: [-0.25, 0.24, 1.45],
        target: [1.65, 1.15, 2.0],
        color: [1, 0.14, 0.018],
        energy: 32,
        sizeMeters: 2.2,
        purpose: 'fill',
        temporalSignalId: 'primary-fire',
        temporalModulation: primaryFireSignal,
      },
      {
        id: 'fire-edge-rim',
        type: 'spot',
        position: [2.9, 2.75, 3.35],
        target: [1.7, 1.25, 2.0],
        color: [1, 0.24, 0.055],
        energy: 58,
        sizeMeters: 0.38,
        angleDegrees: 48,
        purpose: 'rim',
        temporalSignalId: 'primary-fire',
        temporalModulation: primaryFireSignal,
      },
      {
        id: 'cool-night-window-separation',
        type: 'area',
        position: [3.8, 3.5, -2.2],
        target: [1.6, 1.25, 2.0],
        color: [0.12, 0.24, 0.72],
        energy: 245,
        sizeMeters: 3.4,
        purpose: 'environment',
      },
    ],
    metadata: {
      context: 'firelit-interior-with-cool-night-separation',
      contrastStrategy: 'correlated-low-fire-key-bounce-rim-plus-static-cool-environment',
      intendedShotDistance: 'background-to-medium',
      temporalSignals: ['primary-fire'],
      motionDependency: 'none',
    },
  });
}
