import { soundEffectRecipeSchema, type SoundEffectRecipe } from './sound-effect.js';

const recipe = (input: Omit<SoundEffectRecipe, 'schemaVersion' | 'sampleRate' | 'channels'>) =>
  soundEffectRecipeSchema.parse({ schemaVersion: 1, sampleRate: 48000, channels: 2, ...input });

export function createProductionSoundEffectRecipes(): SoundEffectRecipe[] {
  return [
    recipe({
      id: 'audio.sfx.rain-on-stone-ambience',
      durationSeconds: 8,
      targetPeakDb: -5,
      layers: [
        {
          id: 'distant-rain',
          kind: 'noise',
          startSeconds: 0,
          endSeconds: 8,
          gain: 0.42,
          seed: 4101,
          color: 'pink',
          highpassHz: 180,
          lowpassHz: 6200,
          attackSeconds: 0.18,
          releaseSeconds: 0.3,
          pan: -0.35,
          modulationHz: 0.17,
          modulationDepth: 0.22,
        },
        {
          id: 'near-rain',
          kind: 'noise',
          startSeconds: 0,
          endSeconds: 8,
          gain: 0.24,
          seed: 4102,
          color: 'white',
          highpassHz: 1200,
          lowpassHz: 11800,
          attackSeconds: 0.12,
          releaseSeconds: 0.3,
          pan: 0.4,
          modulationHz: 0.31,
          modulationDepth: 0.18,
        },
        {
          id: 'stone-drops-left',
          kind: 'impulse-train',
          startSeconds: 0,
          endSeconds: 8,
          gain: 0.18,
          seed: 4103,
          eventRateHz: 17,
          decaySeconds: 0.018,
          frequencyHz: 2700,
          frequencyJitter: 0.52,
          attackSeconds: 0,
          releaseSeconds: 0.2,
          pan: -0.72,
        },
        {
          id: 'stone-drops-right',
          kind: 'impulse-train',
          startSeconds: 0,
          endSeconds: 8,
          gain: 0.16,
          seed: 4104,
          eventRateHz: 13,
          decaySeconds: 0.022,
          frequencyHz: 2100,
          frequencyJitter: 0.48,
          attackSeconds: 0,
          releaseSeconds: 0.2,
          pan: 0.75,
        },
      ],
      metadata: {
        generator: 'videoer.procedural-sfx.v1',
        category: 'ambience',
        loopIntent: 'extendable-bed',
        environment: 'rain-on-stone',
      },
    }),
    recipe({
      id: 'audio.sfx.wooden-door-open',
      durationSeconds: 1.5,
      targetPeakDb: -3,
      layers: [
        {
          id: 'latch-click',
          kind: 'impulse-train',
          startSeconds: 0.03,
          endSeconds: 0.16,
          gain: 0.46,
          seed: 4201,
          eventRateHz: 18,
          decaySeconds: 0.012,
          frequencyHz: 3300,
          frequencyJitter: 0.18,
          attackSeconds: 0,
          releaseSeconds: 0.04,
          pan: -0.08,
        },
        {
          id: 'hinge-creak',
          kind: 'noise',
          startSeconds: 0.16,
          endSeconds: 1.18,
          gain: 0.62,
          seed: 4202,
          color: 'brown',
          highpassHz: 75,
          lowpassHz: 1650,
          attackSeconds: 0.08,
          releaseSeconds: 0.22,
          pan: 0.12,
          modulationHz: 6.4,
          modulationDepth: 0.78,
        },
        {
          id: 'wood-resonance',
          kind: 'tone',
          startSeconds: 0.19,
          endSeconds: 1.05,
          gain: 0.08,
          frequencyHz: 128,
          endFrequencyHz: 91,
          waveform: 'triangle',
          attackSeconds: 0.04,
          releaseSeconds: 0.24,
          pan: 0,
        },
        {
          id: 'stop-thud',
          kind: 'impulse-train',
          startSeconds: 1.05,
          endSeconds: 1.42,
          gain: 0.7,
          seed: 4203,
          eventRateHz: 3,
          decaySeconds: 0.095,
          frequencyHz: 96,
          frequencyJitter: 0.08,
          attackSeconds: 0,
          releaseSeconds: 0.15,
          pan: 0.18,
        },
      ],
      metadata: {
        generator: 'videoer.procedural-sfx.v1',
        category: 'foley',
        action: 'wooden-door-open',
        syncPointsSeconds: { latch: 0.08, movement: 0.2, stop: 1.08 },
      },
    }),
    recipe({
      id: 'audio.sfx.page-turn-parchment',
      durationSeconds: 0.95,
      targetPeakDb: -5,
      layers: [
        {
          id: 'paper-lift',
          kind: 'noise',
          startSeconds: 0.03,
          endSeconds: 0.58,
          gain: 0.52,
          seed: 4301,
          color: 'pink',
          highpassHz: 520,
          lowpassHz: 9200,
          attackSeconds: 0.08,
          releaseSeconds: 0.12,
          pan: -0.28,
          modulationHz: 8.5,
          modulationDepth: 0.62,
        },
        {
          id: 'paper-edge',
          kind: 'impulse-train',
          startSeconds: 0.18,
          endSeconds: 0.69,
          gain: 0.22,
          seed: 4302,
          eventRateHz: 24,
          decaySeconds: 0.009,
          frequencyHz: 5100,
          frequencyJitter: 0.55,
          attackSeconds: 0.02,
          releaseSeconds: 0.1,
          pan: 0.24,
        },
        {
          id: 'page-settle',
          kind: 'noise',
          startSeconds: 0.56,
          endSeconds: 0.9,
          gain: 0.28,
          seed: 4303,
          color: 'brown',
          highpassHz: 130,
          lowpassHz: 2100,
          attackSeconds: 0.02,
          releaseSeconds: 0.16,
          pan: 0.1,
          modulationHz: 0,
          modulationDepth: 0,
        },
      ],
      metadata: {
        generator: 'videoer.procedural-sfx.v1',
        category: 'foley',
        action: 'page-turn',
        material: 'parchment-paper',
        syncPointsSeconds: { lift: 0.12, cross: 0.42, settle: 0.67 },
      },
    }),
    recipe({
      id: 'audio.sfx.footstep-wet-stone',
      durationSeconds: 0.72,
      targetPeakDb: -3.5,
      layers: [
        {
          id: 'heel-impact',
          kind: 'impulse-train',
          startSeconds: 0.015,
          endSeconds: 0.23,
          gain: 0.72,
          seed: 4401,
          eventRateHz: 5,
          decaySeconds: 0.075,
          frequencyHz: 118,
          frequencyJitter: 0.1,
          attackSeconds: 0,
          releaseSeconds: 0.08,
          pan: -0.04,
        },
        {
          id: 'sole-contact',
          kind: 'noise',
          startSeconds: 0.035,
          endSeconds: 0.36,
          gain: 0.45,
          seed: 4402,
          color: 'brown',
          highpassHz: 90,
          lowpassHz: 1900,
          attackSeconds: 0.012,
          releaseSeconds: 0.13,
          pan: 0.02,
          modulationHz: 0,
          modulationDepth: 0,
        },
        {
          id: 'wet-grit',
          kind: 'noise',
          startSeconds: 0.12,
          endSeconds: 0.62,
          gain: 0.25,
          seed: 4403,
          color: 'white',
          highpassHz: 950,
          lowpassHz: 7600,
          attackSeconds: 0.03,
          releaseSeconds: 0.2,
          pan: 0.08,
          modulationHz: 5.2,
          modulationDepth: 0.42,
        },
      ],
      metadata: {
        generator: 'videoer.procedural-sfx.v1',
        category: 'foley',
        action: 'footstep',
        surface: 'wet-stone',
        syncPointsSeconds: { heel: 0.04, load: 0.16, release: 0.42 },
      },
    }),
  ];
}
